
/*USE JENTI;*/

CREATE TABLE `play_it` (
  `ID` int(15) NOT NULL AUTO_INCREMENT,
  `WORD_ID` int NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE UNIQUE INDEX play_it_idx1 ON play_it (`ID`, WORD_ID);

INSERT INTO play_it (WORD_ID)
SELECT DISTINCT WO.ID
FROM word WO
WHERE WO.LANGUAGE_CODE = 'it'
AND NOT EXISTS 
(
    SELECT WD.ID
    FROM word_definition WD
    WHERE WD.WORD_ID = WO.ID
    AND (WD.DEFINITION IS NULL
    OR LENGTH(TRIM(WD.DEFINITION)) = 0)
)
ORDER BY 1;


/*
CREATE TABLE `PLAY_IT_ANATOMIA` (
  `ID` int(15) NOT NULL AUTO_INCREMENT,
  `WORD_ID` int NOT NULL,
  PRIMARY KEY (`ID`)
);

INSERT INTO PLAY_IT_ANATOMIA (WORD_ID)
SELECT ID
FROM WORD
WHERE LANGUAGE_CODE = 'it'
AND TAGS LIKE '%(anatomia)%'
ORDER BY 1;
*/


CREATE TABLE `play_en` (
  `ID` int(15) NOT NULL AUTO_INCREMENT,
  `WORD_ID` int NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE UNIQUE INDEX play_en_idx1 ON play_en (`ID`, WORD_ID);

INSERT INTO play_en (WORD_ID)
SELECT DISTINCT WO.ID
FROM word WO
WHERE WO.LANGUAGE_CODE = 'en'
AND NOT EXISTS 
(
    SELECT WD.ID
    FROM word_definition WD
    WHERE WD.WORD_ID = WO.ID
    AND (WD.DEFINITION IS NULL
    OR LENGTH(TRIM(WD.DEFINITION)) = 0)
)
ORDER BY 1;
