/*
Copyright 2015 - NINETY-DEGREES

HISTORY

20150417 - user.birthdate
20160105 - user.score ALTER TABLE user ADD SCORE INT(6) DEFAULT 0;
20160117 - word.likes ALTER TABLE word ADD LIKES INT(15) DEFAULT 0;
20160117 -  word_definition.likes ALTER TABLE word_definition ADD LIKES INT(15) DEFAULT 0;

*/

/*USE JENTI;*/

CREATE TABLE `word` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `WORD` VARCHAR(50) NOT NULL,
  `LANGUAGE_CODE` VARCHAR(50) NOT NULL,
  `TYPE` VARCHAR(50) NOT NULL,
  `LIKES` INT(15),
  PRIMARY KEY (`ID`)
);

CREATE UNIQUE INDEX word_idx1 ON word (WORD, LANGUAGE_CODE, `TYPE`);



CREATE TABLE `word_definition` (
  `ID` INT(15) NOT NULL AUTO_INCREMENT,
  `WORD_ID` INT(15) NOT NULL,
  `DEFINITION` VARCHAR(1024) NOT NULL,
  `DEFINITION_SHORT` VARCHAR(50) NOT NULL,
  `SOURCE_NAME` VARCHAR(100) NOT NULL,
  `SOURCE_URL` VARCHAR(256),
  `TAGS` VARCHAR(256),
  `LIKES` INT(15),
  PRIMARY KEY (`ID`)
);

ALTER TABLE word_definition ADD FOREIGN KEY (WORD_ID) REFERENCES WORD (ID);
CREATE UNIQUE INDEX word_definition_idx1 ON word_definition (WORD_ID, SOURCE_NAME, DEFINITION_SHORT);



CREATE TABLE `word_tag` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `TAG` VARCHAR(50) NOT NULL,
  `LANGUAGE_CODE` CHAR(2) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE UNIQUE INDEX word_tag_idx1 ON word_tag (TAG,LANGUAGE_CODE);



CREATE TABLE `word_list` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `WORD` VARCHAR(50) NOT NULL,
  `LANGUAGE_CODE` VARCHAR(50) NOT NULL,
  `AVOID_SOURCES` VARCHAR(1024),
  PRIMARY KEY (`ID`)
);

CREATE UNIQUE INDEX word_list_idx1 ON word_list (WORD, LANGUAGE_CODE);



CREATE TABLE `user` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL,
  `VERIFIED` BOOLEAN DEFAULT FALSE,
  `NAME` VARCHAR(50),
  `BIRTHDATE` DATE,
  `SCORE` INT(6),
  PRIMARY KEY (`ID`)
);

CREATE UNIQUE INDEX user_idx1 ON `user` (EMAIL);



CREATE TABLE `user_word` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(10) NOT NULL,
  `WORD_ID` INT(15) NOT NULL,
  `TAG_ID` INT(10),
  PRIMARY KEY (`ID`)
);

ALTER TABLE user_word ADD FOREIGN KEY (USER_ID) REFERENCES `USER` (ID);
ALTER TABLE user_word ADD FOREIGN KEY (WORD_ID) REFERENCES WORD (ID);
CREATE UNIQUE INDEX user_word_idx1 ON user_word (USER_ID, WORD_ID, TAG_ID);



CREATE TABLE `user_activity` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `CREATED` TIMESTAMP,
  `TYPE` VARCHAR(50),
  `WORD_ID` INT(15),
  `DEFINITION_ID` INT(15),
  `EMAIL` VARCHAR(50),
  `FEEDBACK` VARCHAR(1024),
  `HTTP_USER_AGENT` VARCHAR(128),
  `REMOTE_ADDR` VARCHAR(50),
  PRIMARY KEY (`ID`)
);
